google_call = {
    "kind": "books#volumes",
    "totalItems": 9,
    "items": [
        {
            "kind": "books#volume",
            "id": "OEnZAAAAMAAJ",
            "etag": "BJnQ9/wTQ/A",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/OEnZAAAAMAAJ",
            "volumeInfo": {
                "title": "Studying War--no More?",
                "subtitle": "From Just War to Just Peace",
                "authors": ["Brian Wicker"],
                "publisher": "Eerdmans Publishing Company",
                "publishedDate": "1994",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UOM:39015032306030"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 216,
                "printType": "BOOK",
                "categories": ["Religion"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "1.1.1.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=OEnZAAAAMAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=OEnZAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=OEnZAAAAMAAJ&q=war&dq=war&hl=&cd=1&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=OEnZAAAAMAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/Studying_War_no_More.html?hl=&id=OEnZAAAAMAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=OEnZAAAAMAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "Catholic &quot; Just \u003cb\u003eWar\u003c/b\u003e &quot; Doctrine If we move from the practical approach the Church \u003cbr\u003e\ntook toward waging \u003cb\u003ewar\u003c/b\u003e to doctrine about the issue of \u003cb\u003ewar\u003c/b\u003e , we find that the \u003cbr\u003e\nteaching , like the practice , has undergone profound changes through the \u003cbr\u003e\ncenturies ."
            },
        },
        {
            "kind": "books#volume",
            "id": "4y0eAAAAMAAJ",
            "etag": "2zYRBPBXOgs",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/4y0eAAAAMAAJ",
            "volumeInfo": {
                "title": "War Survival in Soviet Strategy",
                "subtitle": "USSR Civil Defense",
                "authors": ["Leon Gouré"],
                "publishedDate": "1976",
                "description": "Sovjetunionen hævdes at have verdens største civilbeskyttelsesprogram og en evne til at overleve og vinde en ABC-krig. Dette kan bruges i udrenrigspolitikken og kan forrykke terrorbalancen.",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UOM:39015005144483"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 218,
                "printType": "BOOK",
                "categories": ["Civil defense"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "0.2.3.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=4y0eAAAAMAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=4y0eAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=4y0eAAAAMAAJ&q=war&dq=war&hl=&cd=2&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=4y0eAAAAMAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/War_Survival_in_Soviet_Strategy.html?hl=&id=4y0eAAAAMAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=4y0eAAAAMAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "the bourgeois pacifists &#39; arguments about “ the end of the world ” in such a \u003cb\u003ewar\u003c/b\u003e \u003cbr\u003e\nand the impossibility of victory benefit only the aggressor and the nuclear \u003cbr\u003e\nmaniacs , who would very much like one or other of those against whom they are\u003cbr\u003e\n&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "p1q4viwEmMUC",
            "etag": "exiX8WxT1jU",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/p1q4viwEmMUC",
            "volumeInfo": {
                "title": "National War Agencies Appropriation Bill. Hearings",
                "authors": [
                    "United States. Congress. House. Committee on Appropriations"
                ],
                "publishedDate": "1944",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UOM:39015084950826"}
                ],
                "readingModes": {"text": False, "image": False},
                "printType": "BOOK",
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "1.0.1.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=p1q4viwEmMUC&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=p1q4viwEmMUC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=p1q4viwEmMUC&q=war&dq=war&hl=&cd=3&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=p1q4viwEmMUC&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/National_War_Agencies_Appropriation_Bill.html?hl=&id=p1q4viwEmMUC",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=p1q4viwEmMUC&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "COMMENTS ON OFFICE OF \u003cb\u003eWAR\u003c/b\u003e INFORMATION PRODUCTIONS The \u003cbr\u003e\nfollowing are representative press comments on films produced by the Office of \u003cbr\u003e\n\u003cb\u003eWar\u003c/b\u003e Information , Bureau of Motion Pictures . THE WORLD AT \u003cb\u003eWAR\u003c/b\u003e A \u003cbr\u003e\nremarkable \u003cb\u003ewar\u003c/b\u003e film&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "aSFaAAAAYAAJ",
            "etag": "bRYCPklmgEc",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/aSFaAAAAYAAJ",
            "volumeInfo": {
                "title": "World War II",
                "subtitle": "A Student Companion",
                "authors": ["William L. O'Neill"],
                "publisher": "Oxford University Press, USA",
                "publishedDate": "1999",
                "description": "Entries describing the causes, events, weapons, leaders, and other developments of the war are accompanied by lists of dates and of museums and historic sites",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "PSU:000045371264"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 384,
                "printType": "BOOK",
                "categories": ["Juvenile Nonfiction"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "0.1.1.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=aSFaAAAAYAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=aSFaAAAAYAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=aSFaAAAAYAAJ&q=war&dq=war&hl=&cd=4&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=aSFaAAAAYAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/World_War_II.html?hl=&id=aSFaAAAAYAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=aSFaAAAAYAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "PENN STATE UNIVERSITY LIBRARIES A0l][]DLl53?1iEEi WORLD \u003cb\u003eWAR\u003c/b\u003e II orld \u003cbr\u003e\n\u003cb\u003eWar\u003c/b\u003e H was the bloodi&#39; E est and farthest-reaching military conflict in human \u003cbr\u003e\nhistory and forever changed how we view the world. This authoritative and \u003cbr\u003e\nthorough&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "iKQfAAAAMAAJ",
            "etag": "xFa1QjfmRiQ",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/iKQfAAAAMAAJ",
            "volumeInfo": {
                "title": "Drives Toward War",
                "authors": ["Edward Chace Tolman"],
                "publishedDate": "1942",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UOM:39015008102637"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 118,
                "printType": "BOOK",
                "categories": ["Psychophysiology"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "2.2.3.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=iKQfAAAAMAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=iKQfAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=iKQfAAAAMAAJ&q=war&dq=war&hl=&cd=5&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=iKQfAAAAMAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/Drives_Toward_War.html?hl=&id=iKQfAAAAMAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=iKQfAAAAMAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "ponents in the prosecution of a \u003cb\u003ewar\u003c/b\u003e are , I believe , all around us . We observe it \u003cbr\u003e\nin our friends and in ourselves as well as most definitely in the Nazis and the \u003cbr\u003e\nJapanese . But as more objective , less prejudiced evidence let me cite a récent&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "M0ogAQAAIAAJ",
            "etag": "D1+msXl6PeU",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/M0ogAQAAIAAJ",
            "volumeInfo": {
                "title": "Nigerian Writers on the Nigerian Civil War",
                "subtitle": "Anguish, Commitment, Catharsis",
                "authors": ["Olu Obafemi"],
                "publishedDate": "1992",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "STANFORD:36105021144188"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 77,
                "printType": "BOOK",
                "categories": ["Nationalism and literature"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "1.1.2.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=M0ogAQAAIAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=M0ogAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=M0ogAQAAIAAJ&q=war&dq=war&hl=&cd=6&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=M0ogAQAAIAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/Nigerian_Writers_on_the_Nigerian_Civil_W.html?hl=&id=M0ogAQAAIAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=M0ogAQAAIAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "experiences in the \u003cb\u003ewar\u003c/b\u003e , Nigcrian writers felt the urgent need to go beyond mere \u003cbr\u003e\ndescriptions of the horrors of \u003cb\u003ewar\u003c/b\u003e to spread general enlightenment and sow the \u003cbr\u003e\nseed of spiritual and social regeneration in their community after the \u003cbr\u003e\ndisorientation&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "7EQpAQAAMAAJ",
            "etag": "EWOZdC6EKsM",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/7EQpAQAAMAAJ",
            "volumeInfo": {
                "title": "There's a War to Be Won",
                "subtitle": "The United States Army in World War II",
                "authors": ["Geoffrey Perret"],
                "publisher": "Ballantine",
                "publishedDate": "1997",
                "description": "THERE'S A WAR TO BE WON is the landmark story of one of the greatest armies in history, a conscript force of amateur soldiers who had an unparalleled record of combat success. Here -- for the first time in one volume -- is the chronicle of the United States Army's dramatic mobilization and stunning march to victory in World War II. In a lively and engrossing narrative that spans theaters of operations around the world, Geoffrey Perret tells how the Army was drafted, trained, organized, armed, and led at every stage of the war. Beginning with the prescient military planners of the 1930s, he offers vivid warts-and-all profiles of the farsighted commanders who would lead the way, men like Marshall, MacArthur, Eisenhower, Ridgway, Bradley, and Patton. Drawing heavily on important new source material in major archives throughout the United States, THERE'S A WAR TO BE WON offers new insights into the wartime Army, its commanders, and its battles. A major work of American military history. \"An immensely readable, well-researched history . . . Dramatic.\" -- Chicago Tribune From the Paperback edition.",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "NWU:35556030669881"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 656,
                "printType": "BOOK",
                "categories": ["History"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "0.3.2.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=7EQpAQAAMAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=7EQpAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=7EQpAQAAMAAJ&q=war&dq=war&hl=&cd=7&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=7EQpAQAAMAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/There_s_a_War_to_Be_Won.html?hl=&id=7EQpAQAAMAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=7EQpAQAAMAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "The president and much of the country assumed that in the event of the United \u003cbr\u003e\nStates &#39; entering the \u003cb\u003ewar\u003c/b\u003e victory was inevitable because the United States could \u003cbr\u003e\neasily outproduce its enemies . Not for the first time - or the last — the nation was\u003cbr\u003e\n&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "DqFDAAAAIAAJ",
            "etag": "6a87g9e3qQ8",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/DqFDAAAAIAAJ",
            "volumeInfo": {
                "title": "The Study of War",
                "subtitle": "An Inaugural Lecture Delivered Before the University of Oxford on 23 February 1926",
                "authors": ["Ernest Dunlop Swinton"],
                "publishedDate": "1926",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UCAL:$B15916"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 26,
                "printType": "BOOK",
                "categories": ["War"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "0.2.2.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=DqFDAAAAIAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=DqFDAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=DqFDAAAAIAAJ&q=war&dq=war&hl=&cd=8&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=DqFDAAAAIAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/The_Study_of_War.html?hl=&id=DqFDAAAAIAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=DqFDAAAAIAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "Clausewitz&#39;s definition is that \u003cb\u003ewar\u003c/b\u003e is an act of violence intended to compel our \u003cbr\u003e\nopponents to fulfil our will. I think, however, that it now comprises more than was \u003cbr\u003e\ndreamed of by that great thinker, who has for years been accepted as a leading&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "UP7W6dnELLgC",
            "etag": "LqZ7aLvNfbE",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/UP7W6dnELLgC",
            "volumeInfo": {
                "title": "The Civil War and the American System",
                "subtitle": "America's Battle with Britain, 1860-1876",
                "authors": ["W. Allen Salisbury"],
                "publishedDate": "1992",
                "industryIdentifiers": [
                    {"type": "ISBN_10", "identifier": "0943235065"},
                    {"type": "ISBN_13", "identifier": "9780943235066"},
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 440,
                "printType": "BOOK",
                "categories": ["Great Britain"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "1.1.1.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=UP7W6dnELLgC&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=UP7W6dnELLgC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=UP7W6dnELLgC&q=war&dq=war&hl=&cd=9&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=UP7W6dnELLgC&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/The_Civil_War_and_the_American_System.html?hl=&id=UP7W6dnELLgC",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=UP7W6dnELLgC&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "The ensuing newspaper \u003cb\u003ewar\u003c/b\u003e between Carey and Cobbett eventually led to the \u003cbr\u003e\ndissolution of Cobbett &#39; s Pennsylvania newspaper , the Peter Porcupine Gazette \u003cbr\u003e\n, and his departure to England . It was only with the defeat of the “ League of&nbsp;..."
            },
        },
        {
            "kind": "books#volume",
            "id": "7mXjAAAAMAAJ",
            "etag": "ObxuQRkyjRU",
            "selfLink": "https://www.googleapis.com/books/v1/volumes/7mXjAAAAMAAJ",
            "volumeInfo": {
                "title": '"Food for War" in Southeast Asia',
                "subtitle": "U.S. Food Aid Policy, 1973-1987",
                "authors": ["Marc J. Cohen"],
                "publishedDate": "1988",
                "industryIdentifiers": [
                    {"type": "OTHER", "identifier": "UOM:39015076519225"}
                ],
                "readingModes": {"text": False, "image": False},
                "pageCount": 27,
                "printType": "BOOK",
                "categories": ["Economic assistance, American"],
                "maturityRating": "NOT_MATURE",
                "allowAnonLogging": False,
                "contentVersion": "1.1.2.0.preview.0",
                "panelizationSummary": {
                    "containsEpubBubbles": False,
                    "containsImageBubbles": False,
                },
                "imageLinks": {
                    "smallThumbnail": "http://books.google.com/books/content?id=7mXjAAAAMAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
                    "thumbnail": "http://books.google.com/books/content?id=7mXjAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                },
                "language": "en",
                "previewLink": "http://books.google.pl/books?id=7mXjAAAAMAAJ&q=war&dq=war&hl=&cd=10&source=gbs_api",
                "infoLink": "http://books.google.pl/books?id=7mXjAAAAMAAJ&dq=war&hl=&source=gbs_api",
                "canonicalVolumeLink": "https://books.google.com/books/about/Food_for_War_in_Southeast_Asia.html?hl=&id=7mXjAAAAMAAJ",
            },
            "saleInfo": {
                "country": "PL",
                "saleability": "NOT_FOR_SALE",
                "isEbook": False,
            },
            "accessInfo": {
                "country": "PL",
                "viewability": "NO_PAGES",
                "embeddable": False,
                "publicDomain": False,
                "textToSpeechPermission": "ALLOWED",
                "epub": {"isAvailable": False},
                "pdf": {"isAvailable": False},
                "webReaderLink": "http://play.google.com/books/reader?id=7mXjAAAAMAAJ&hl=&printsec=frontcover&source=gbs_api",
                "accessViewStatus": "NONE",
                "quoteSharingAllowed": False,
            },
            "searchInfo": {
                "textSnippet": "During the debate over this proposal in the House of Representatives , one \u003cbr\u003e\nmember noted that 90 percent of the omn were proceeds from the sale of PL 480 \u003cbr\u003e\ncommodities in South Vietnam already were going to support the \u003cb\u003ewar\u003c/b\u003e effort , with\u003cbr\u003e\n&nbsp;..."
            },
        },
    ],
}
