# Generated by Django 3.2.5 on 2021-07-30 16:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("published_date", models.CharField(max_length=10, null=True)),
                ("average_rating", models.FloatField(default=0)),
                ("ratings_count", models.IntegerField(default=0)),
                ("thumbnail", models.URLField(null=True)),
                ("authors", models.ManyToManyField(to="main.Author")),
                ("categories", models.ManyToManyField(to="main.Category")),
            ],
        ),
    ]
